export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

plugins=(git)

source $ZSH/oh-my-zsh.sh

prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)%n"
  fi
}

# aliases

alias lla="ls -la"

[ -f .aliases ] && source .aliases


# typewriter prompt theme

fpath=($fpath "$HOME/.zfunctions")
autoload -U promptinit; promptinit
prompt typewritten

