export ZSH="$HOME/.oh-my-zsh"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# aliases

alias lla="ls -la"
alias addrefs="git config remote.origin.fetch \"+refs/heads/*:refs/remotes/origin/*\""
alias dockerls="docker container ls --format '{{.ID}} -> {{.Names}} ({{.Status}}) :: {{.Ports}}'"
alias dockerlst="docker container ls --format 'table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}'"

[ -f .aliases ] && source .aliases

# typewritten prompt theme
# install via `npm install --location=global typewritten`

fpath=($fpath "$HOME/.zfunctions")
autoload -U promptinit; promptinit
export TYPEWRITTEN_RELATIVE_PATH="home"
prompt typewritten

fpath=($fpath "/Users/laurent/.zfunctions")

# volta

export PATH=/Users/laurent/.volta/bin:$PATH
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
