ZSH_THEME="theunraveler" # set by `omz`

export ZSH="$HOME/.oh-my-zsh"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# aliases

unalias -m '*'
alias ll="ls -l --color"
alias lla="ls -la --color"
alias addrefs="git config remote.origin.fetch \"+refs/heads/*:refs/remotes/origin/*\""
alias dockerls="docker container ls --format '{{.ID}} -> {{.Names}} ({{.Status}}) :: {{.Ports}}' | sort -k 3"
alias dockerlst="docker container ls --format 'table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}' | tail -n +2 | sort -k 2"

endquarantine() {
    xattr -rd com.apple.quarantine /Applications/$1.app
}

[ -f .aliases ] && source .aliases

fpath=($fpath "$HOME/.zfunctions")
autoload -U promptinit; promptinit

fpath=($fpath "/Users/laurent/.zfunctions")

# volta

export PATH=/Users/laurent/.volta/bin:$PATH
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

source /Users/laurent/.docker/init-zsh.sh || true # Added by Docker Desktop
