# theme

ZSH_THEME="theunraveler" # set by `omz`

export ZSH="$HOME/.oh-my-zsh"

source $ZSH/oh-my-zsh.sh

# aliases

unalias -m '*'
alias ll="ls -l --color"
alias lla="ls -la --color"
alias addrefs="git config remote.origin.fetch \"+refs/heads/*:refs/remotes/origin/*\""
alias dockerls="docker container list --format 'table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}' | tail -n +2 | sort -k 2"
alias dockerlsa="docker container list -a --format 'table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}' | tail -n +2 | sort -k 2"
alias gitlog="git log --max-count=5 --oneline | cat"
alias openinsublime="open -a Sublime\ Text ."
alias rmr="rm -r"

endquarantine() {
    xattr -rd com.apple.quarantine /Applications/$1.app
}

[ -f .aliases ] && source .aliases

# paths

fpath=($fpath "$HOME/.zfunctions")
autoload -U promptinit; promptinit

fpath=($fpath "/Users/laurent/.zfunctions")

# volta

export PATH=/Users/laurent/.volta/bin:$PATH
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# misc

source /Users/laurent/.docker/init-zsh.sh || true # Added by Docker Desktop
